### ISSUE TITLE
Replace WS library to gorilla/websocket

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/arikawa#11]
## Preamble

As found out by someone on the Discord, `nhooyr.io/websocket` pulls down very heavy dependencies.

![image](https://user-images.githubusercontent.com/8463786/78059895-87ff2280-733f-11ea-9ad3-43b978481839.png)

## Proposal

Change the Websocket library. There are 2 prominent proposals: [gorilla/websocket](https://github.com/gorilla/websocket) and [gobwas/ws](https://github.com/gobwas/ws).

These libraries above don't have mutices to protect Writes, but we could reuse our current mutex for that. 

`gorilla/websocket` does not depend on any external dependencies (as shown by its `go.mod` file), making it a pretty good alternative. 

`gobwas/ws` on the other hand seem to be more memory-friendly, however does not use Go Modules, making it less of an ideal alternative.

**Comment by nhooyr** [comment]
Opened https://github.com/nhooyr/websocket/issues/220

**Comment by nhooyr** [comment]
You can also use an older version without compression support for now.
