### ISSUE TITLE
json: cannot unmarshal number 133424 into Go struct field User.user.flags of type discord.UserFlags

### ISSUE THREAD

**Issue by Juby210** [diamondburned/arikawa#119]
```
Failed to connect to Discord: Failed to start gateway: WS handler error on first event: Failed to parse event READY: json: cannot unmarshal number 133424 into Go struct field User.user.flags of type discord.UserFlags
```
my account has verified bot developer and hs balance badge and it breaks arikawa

**Comment by mavolin** [comment]
Seeing you seem to use an older version of arikawa (errors haven't been upper-case since v.0.8.2), does this reproduce with the latest version?

**Comment by Juby210** [comment]
i tested it with gtkcord3 and seems like gtkcord uses latest arikawa

**Comment by Juby210** [comment]
ok nvm, everything works great
