### ISSUE TITLE
Command aliases and custom checks

### ISSUE THREAD

**Issue by ks129** [diamondburned/arikawa#12]
### Command aliases
Add a way to add aliases to command. This should be done like this:
```go
bot.AddAlias("command", "alias")
```

### Custom checks
Add custom checks. Implementation should similar like aliases:
```go
bot.AddCheck("command", CheckFunction)
```

**Comment by diamondburned** [comment]
What is this check API? Is it similar to middlewares for individual commands?

**Comment by ks129** [comment]
Check is basically individual command middleware yes. This will be run before command execution and check must return boolean. `true` means the command will be executed, `false` means that no permissions and command will be not executed.

**Comment by diamondburned** [comment]
Check feels very niche. Is there a reason why you're not doing it for only one command?

The router already has a middleware for the entire subcommand, if you want to use one middleware for multiple commands.

**Comment by ks129** [comment]
@diamondburned I think this should be useful for cooldowns, and however, current most used libraries provide ways to make check, so I think this should be useful in here too. Like there is a group of commands, but one command of these is for only for VIP users, so you have to make a request to DB and fetch info about user, and this should not apply to every command in a group.

**Comment by diamondburned** [comment]
I'm saying to just append the check at the start of the function. Other libraries don't take an approach like this, so doing such a feature is as easy as another condition check. This library is reflect-based, meaning it's already complex as it is.

I do plan on implementing command aliases soon, but I'll leave this issue open for aliases. PRs welcomed.

**Comment by diamondburned** [comment]
Custom checks or middlewares to be implemented in https://github.com/diamondburned/arikawa/issues/24, funnily enough.

I'll do aliases later, I suppose.

**Comment by ks129** [comment]
Aliases are done in #107
