### ISSUE TITLE
Bot: v2: Slash Commands

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/arikawa#176]
The new Discord API seems to have introduced a new API called [Slash Commands](https://github.com/discord/discord-api-docs/blob/feature/interactions/docs/interactions/Slash_Commands.md), which seems to introduce a JSON schema for describing all commands to be handled using something called "integrations."

Since this is a fairly new feature that should be integrated into the Bot framework, I propose the following steps:

- [x] Add integration events and structs into package `discord`, `api` and `gateway`.
- [x] Add support for `*gateway.InteractionCreateEvent` in the `bot` package
    - [x] Support for converting commands and subcommands that implement said event to the JSON format
    - [x] Use the integration token for replies
- [ ] Make a small `net/http` abstraction to easily allow bots be created using the webhook API
    - [ ] Ideally standalone without `gateway` to allow for small serverless bots

**Comment by zoeleu** [comment]
Is there a way to do this right *now* with the current API?

**Comment by samhza** [comment]
@matteoturini yes, look at the v3 branch
https://pkg.go.dev/github.com/diamondburned/arikawa/v3

**Comment by diamondburned** [comment]
The v3 branch should work if you don't plan on using slash commands with the
`bot` package. It'll take a lot more work on that package for it to work with
slash commands that the changes may as well not be implemented.

**Comment by diamondburned** [comment]
As a sidenote, this issue should probably be closed once v3 is stabilized.

**Comment by diamondburned** [comment]
Closing since `v3.0.0` release candidate tags are available for use, and the `v3` branch has been the default branch for a while now.

As a sidenote, `go get`ting `github.com/diamondburned/arikawa/v3` should fetch the latest release candidate.
