### ISSUE TITLE
Gateway: v2: MessageReactionAddEvent is not working

### ISSUE THREAD

**Issue by nupamore** [diamondburned/arikawa#186]
I just upgraded it with v2 in the same code, but it doesn't work.
`MessageCreateEvent` works well for both v1 and v2
`MessageReactionAddEvent` works only v1

```
ctx.AddHandler(func(r *gateway.MessageReactionAddEvent) {
	log.Println("react")
})
```

**Comment by mavolin** [comment]
Are you using the correct intents?

This works for me:

```go
s, err := state.New("Bot XXX")
if err != nil {
    log.Fatal(err)
}

s.Gateway.AddIntents(gateway.IntentDirectMessageReactions)
s.AddHandler(func(r *gateway.MessageReactionAddEvent) {
    log.Println("react")
})

if err := s.Open(); err != nil {
    log.Fatal(err)
}

select {}
```

**Comment by diamondburned** [comment]
Did you change `gateway`'s import to v2?

**Comment by nupamore** [comment]
I solved it by adding `IntentGuildMessageReactions`. Thank you for giving me a hint. @mavolin 

The reason for the problem is used this code. When starting with `state.New()` results show error, but starting with `bot.Start()` does not show the error and only the reaction event has stopped working.
```go
// set activity
ctx.Gateway.Identifier.IdentifyData = gateway.IdentifyData{
	Token: token,
	Presence: &gateway.UpdateStatusData{
		Activities: []discord.Activity{{
			Name: configs.Env["BOT_STATUS"],
			Type: discord.GameActivity,
		}},
		Status: gateway.OnlineStatus,
	},
}
```

**Comment by diamondburned** [comment]
> When starting with state.New() results show error, but starting with bot.Start() does not show the error and only the reaction event has stopped working.

`bot.Start()` implicitly derives the required intents, but it is not aware of internal handlers not added through `bot`.

Since this issue is solved, I'll go ahead and close it. `AddIntents` mutates `IdentifyData` directly, so I don't see it as a bug. To prevent future problems, you can set just the `Presence` field like so:

```go
ctx.Gateway.Identifier.IdentifyData.Presence = &gateway.UpdateStatusData{}
```

**Comment by nupamore** [comment]
Thank you for your kindness.
