### ISSUE TITLE
Error is never checked

### ISSUE THREAD

**Issue by karitham** [diamondburned/arikawa#219]
I'm not sure how the flow is supposed to go, but shouldn't this error be returned?
 
Right now, it is discarded since every other return is `return nil`.

https://github.com/diamondburned/arikawa/blob/68d29cdb6a4b1b5257b87fae12b92a98dfd40c1d/bot/ctx_call.go#L53-L53

**Comment by diamondburned** [comment]
Closed in b1cae78.
