### ISSUE TITLE
Add Owner Only command flag

### ISSUE THREAD

**Issue by ks129** [diamondburned/arikawa#22]
`O` flag should be added and commands that have this flag can be run only by the owner of bot.

**Comment by diamondburned** [comment]
How would you know who the owner is?

**Comment by ks129** [comment]
@diamondburned You can get it from application information. This should handle teams too.

**Comment by diamondburned** [comment]
That's too niche. Having multiple arguments for one specific thing in the router wouldn't work.

Ideally, you'd either get it from the API or the application implements it by itself.

**Comment by ks129** [comment]
Or maybe add Owner IDs defining?

**Comment by diamondburned** [comment]
That won't do, as I said above.

**Comment by diamondburned** [comment]
I have an idea.

**Comment by diamondburned** [comment]
If https://github.com/diamondburned/arikawa/issues/24 gets implemented, you should be able to do the following:

```go
const OwnerID = 694201337123123

func (cmds *Commands) Setup(sub *bot.Subcommand) {
	// Add a middleware for all methods (*). The intake argument could also be
	// an interface{}.
	sub.AddMiddleware("*", func(c *gateway.MessageCreateEvent) error {
		if c.Author.ID != OwnerID {
			return bot.Break // silently break the chain
		}
		return nil // continue the chain
	})
}
```
