### ISSUE TITLE
VoiceStates not in sync

### ISSUE THREAD

**Issue by drunlade** [diamondburned/arikawa#220]
I admit I haven't dug very deep into this one, but on the face of it it seems voice states don't reflect the truth. Take this middleware example:
```go
func VCOnly(ctx *bot.Context) func(interface{}) error {
	return func(ev interface{}) error {
		var channelID = infer.ChannelID(ev)
		if !channelID.IsValid() {
			return bot.Break
		}

		var userID = infer.UserID(ev)
		if !userID.IsValid() {
			return bot.Break
		}

		// TODO: Apparently voice states are cached or last outside of a user disconnect

		states, err := ctx.VoiceStates(infer.GuildID(ev))
		if err != nil && err.Error() != "item not found in store" {  //TODO: Use error constant
			// Apparently no voice states triggers an error which
			// isn't terribly helpful, so need to filter it out
			return err
		}

		for _, state := range states {
			if state.UserID == userID {
				// User is in VC so all good
				return nil
			}
		}

		return errors.New("You must be in VC to use this commend")
	}
}
```
It works at first, blocks a user who isn't in VC. They join. It lets them use the command. They leave VC and... it still lets them use the command. I'm guessing there is something about the nature of how the states are updated that causes this.

**Comment by diamondburned** [comment]
Have you tried checking for `state.ChannelID.IsValid()`?

**Comment by diamondburned** [comment]
Also, as a side-note, the error constant you're looking for is `store.ErrNotFound`.

**Comment by drunlade** [comment]
I did not try `state.ChannelID.IsValid()` but that does indeed resolve that issue. I didn't think to try it as I assumed the `ID` would be valid regardless of being connected or not, since it's the channel ID and the channel is there and valid. I'd suggest maybe `IsValid()` should exist on the `state` as that is far more intuitive and from a code perspective "Says what it means".

Since I'm here btw I'm really enjoying working with this lib, really easy to work with once I got my head around the different approach to the other discord libs.

**Comment by drunlade** [comment]
Also I found the error under `state.ErrStoreNotFound`  ;)

**Comment by drunlade** [comment]
Issue resolved with a code change, thanks to @diamondburned for pointing it out.

**Comment by diamondburned** [comment]
> I'd suggest maybe `IsValid()` should exist on the `state` as that is far more intuitive and from a code perspective "Says what it means".

This turns out to be a bug. I'll be pushing a commit that fixes this on both v2 and v3.

**Comment by fishuke** [comment]
@diamondburned is this still an issue?

**Comment by diamondburned** [comment]
> @diamondburned is this still an issue?

I don't think so.
