### ISSUE TITLE
Message.Content is empty

### ISSUE THREAD

**Issue by patlux** [diamondburned/arikawa#227]
Hi,

I'm trying to implement a simple message forwarder to forward specific messages from one server to another. To do this, I need to use a user token instead of a bot token. I know it's against the TOS. But it's just for private use.

For that purpose I need access to each incoming message including their content. But it seems to be always `""` when using a user token instead of a bot token.

```go
func Start() {
	var token = os.Getenv("DISCORD_TOKEN")
	if token == "" {
		log.Fatalln("No $DISCORD_TOKEN given.")
	}

	s, err := state.New(token)
	if err != nil {
		log.Fatalln("Session failed:", err)
	}

	s.AddHandler(func(c *gateway.MessageCreateEvent) {
		log.Printf("%v (%v): \"%v\"", c.Author.Username, c.ChannelID, c.Content)
	})

	s.Gateway.AddIntent(gateway.IntentGuildMessages)
	s.Gateway.AddIntent(gateway.IntentDirectMessages)

	if err := s.Open(); err != nil {
		log.Fatalln("Failed to connect:", err)
	}
	defer s.Close()

	u, err := s.Me()
	if err != nil {
		log.Fatalln("Failed to get myself:", err)
	}

	log.Println("Started as", u.Username)

	// Block forever.
	select {}
}
```

I tried the same with `discord.js` and it works fine. Why it doesn't work this this implementation? It's also not working with `godiscord`.

Best regards,
Patrick

**Comment by diamondburned** [comment]
You're not supposed to have intents with user accounts. I'm surprised the gateway even connected.

Also as a sidenote, instead of doing `\"%v\"`, you can use `%q`.

**Comment by patlux** [comment]
So there is no way to accomplish this with a user account and this library?

Oh, thanks for the hint! I'm new in go and thought that would be a good first project in go :)

**Comment by diamondburned** [comment]
What I meant was that you have to remove the intents for it to work. I think.

If you want an example of using user accounts with this library, you can check out [diamondburned/cchat-discord](https://github.com/diamondburned/cchat-discord), which is an adapter library that provides code for a Discord chat client.

**Comment by patlux** [comment]
Ah thank you a lot. I thought the intents are used to register the events.

Now it works as expected.
