### ISSUE TITLE
also handle SIGTERM graceful shutdown

### ISSUE THREAD

**Issue by jxsl13** [diamondburned/arikawa#229]
In a docker context containers are shutdown via the SIGTERM signal.
Would be nice to also handle that signal gracefully

It can be found in `syscall.SIGTERM`

**Comment by diamondburned** [comment]
Is this available on Windows?

**Comment by jxsl13** [comment]
https://stackoverflow.com/questions/47306805/signal-sigterm-not-received-by-subprocess-on-windows

as long as you don't fork your process, seemingly yes.
