### ISSUE TITLE
fix(api): no retries on error

### ISSUE THREAD

**Issue by mavolin** [diamondburned/arikawa#25]
Regarding: `httputil.Client.Request`

Currently, `Request` retries on any HTTP Response status that is `< 200` or `> 299`.
However, many errors won't get resolved by a retry, as only 5xx errors indicate a server error and any other status indicates either an error with the data that was sent, etc..
An exception to this is of course code `429 - too many requests` which indicates rate limiting.
See also https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.

I would propose to check for server or rate limit errors and retry only then, but let all others break the loop and get handled respectively.
This could be done by simply replacing the
```go
if status = r.GetStatus(); status < 200 || status > 299 {
    continue
}
```
with
```go
if status = r.GetStatus(); status == http.StatusTooManyRequests || status >= 500 {
    continue
}
```
.

If you create a branch for it, I can hand in a PR for it.

**Comment by diamondburned** [comment]
You can PR straight into master, that's fine.

**Comment by mavolin** [comment]
Wow, that was quick! Will do.
