### ISSUE TITLE
v3: Support `X-Audit-Log-Reason`-Header

### ISSUE THREAD

**Issue by mavolin** [diamondburned/arikawa#253]
Some endpoints, e.g. Start Thread With Message, now have a note saying they support the `X-Audit-Log-Reason` header. Presumably, this header allows to specify a reason that is added to the audit log entry the action causes.
We should add support for this, by adding `Reason string` fields to the `XData` structs, as well as `XWithReason` methods for those methods that don't take in a data struct.

**Comment by diamondburned** [comment]
This being a header makes me wonder if this header applies for all POST/PUT methods, and that if it'd be better for them to just be part of the HTTP client (like how `context.Context` is) instead of dirtying some cleaner methods w/ the parameter.

**Comment by ayntee** [comment]
> This being a header makes me wonder if this header applies for all POST/PUT methods...

No, this header is not applicable for all POST/PUT methods. [This PR](https://github.com/discord/discord-api-docs/pull/3421) documented all endpoints that support the `X-Audit-Log-Reason` header.

**Comment by mavolin** [comment]
To be honest I can see advantages for both sides. Adding the headers using the http client will definitively be easier to implement in terms of time. However, it is a lot more unsafe in that it doesn't restrict usage to only those endpoints, that actually allow it. If one uses it incorrectly, no error will be returned, making it less obvious why no reason is being added.
Furthermore, I'm not a big fan of the chaining this will require:
```go
s.ModifyChannel(channelID, api.ModifyChannelData{
    Name: "new-name",
    Reason: "Wumpus told me to",
})
```
seems cleaner and has a better glanceability, than
```go
s.WithReason("Wumpus told me to").
    ModifyChannel(channelID, api.ModifyChannelData{
        Name: "new-name",
    })
```

However, seeing as not all affected endpoints take in a data struct, we would either need to create `XWithReason` methods, or add a reason parameter, that is ignored if empty to those remaining endpoints.

Both solutions are not ideal, however, I personally would opt for adding `Reason` fields to data structs, and creating `XWithReason` methods where we can't. In my opinion the tradeoff is smaller and we gain the bonus of having a safer, more explicit (as in, you can add a reason to this action, but not to that) solution with better glanceability.

**Comment by diamondburned** [comment]
> I personally would opt for adding `Reason` fields to data structs, and creating `XWithReason` methods where we can't.

Perhaps, it might be a better idea to make all methods that can take in `Reason` have a data variant, then have 1 or so shorthand functions.

We can then use a small abstraction in `httputil` that checks for headers:

```go
type AuditLogReason struct {
	Reason string `json:"reason"`
}

// Header returns the headers that this data structure adds to a HTTP request.
func (r AuditLogReason) Header() http.Header {
	if r.Reason == "" { return nil }

	return http.Header{
		"X-Audit-Log-Reason": sanitize(r.Reason),
	}
}

type ModifyChannelData struct {
	Name string ...

	AuditLogReason
}
```

This change does match what I eventually want to do with gateway events, that is to have a `type Event interface` that describes both the event type and its OP code without needing the caller to explicitly state it. This will help getting rid of all the type-specific send methods in the gateway, as well as its context variants.

Concretely, it would be something like this:

```go
type Event interface {
	OP() int
}

type DispatchEvent interface {
	Event
	Type() string
}

type dispatchEvent struct{}

func (e dispatchEvent) OP() int { return DispatchOP }

type MessageCreateEvent struct {
	dispatchEvent

	// fields
}

func (e MessageCreateEvent) Type() string { return "MESSAGE_CREATE" }
```

**Comment by mavolin** [comment]
I don't like this because it would require unnecessary nesting when using data structs. The above example would become:
```go
s.ModifyChannel(channelID, api.ModifyChannelData{
    Name: "new-name",
    AuditLogReason: httputil.AuditLogReason{
        Reason: "Wumpus told me too",
    },
})
```
Therefore, I still prefer the original proposal. I am fine with adding data structs to every endpoint that allows reasons, however.

**Comment by diamondburned** [comment]
You can do `type AuditLogReason string` then. The parent type would have to implement `Header()`, though.

Edit: or not. https://play.golang.org/p/vUxelwLxHwX

**Comment by mavolin** [comment]
SGTM. But wouldn't it make more sense to put AuditLogReason into package `api`, since this is specific to discord's api?

**Comment by diamondburned** [comment]
That makes sense.
