### ISSUE TITLE
Reconnecting to voice immediately after disconnecting does not work

### ISSUE THREAD

**Issue by samhza** [diamondburned/arikawa#288]
I wrote a [test program](https://gist.github.com/samhza/0e0ff06ffc391f94c0425cb1e94c6c2a) that demonstrates this bug. The program exits with an error `second time: joining the voice channel: failed to open voice gateway: missing endpoint in state`.

**Comment by nbulischeck** [comment]
I have a similar issue doing the same thing but it's slightly different:

```
2021/11/15 10:25:07 Gateway error: pace failed, reconnecting: websocket is closed
2021/11/15 10:25:07 failed to join voice channel: failed to open voice gateway: failed to wait for Ready or Resumed: WS error: websocket: close 4006: Session is no longer valid.
```

**Comment by samhza** [comment]
The bug no longer occurs in the test program I sent.
