### ISSUE TITLE
Unecessary Pointers

### ISSUE THREAD

**Issue by mavolin** [diamondburned/arikawa#29]
Commit 619558ecabca782974d73768e728ddd27bf32dd8 introduced the idea, that fields, not required by discord should be made nillable, to allow the developer to explicitly omit them, as go types cannot be nil unless they are pointers (or slices, maps etc.). While this may be advisable for bools and (regular) numbers, it makes no sense for `discord.Snowflake`.
A valid Snowflake will, for obvious reason, never be zero, so a simple `omitempty` should suffice, as the godoc of `json.Unmarshal` confirms.

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.

Enforcing pointers on `Snowflake`s requires code like this, as there are no utility functions for this case, as there are for `json.OptionInt` etc.
And also why make something hard if it doesn't have to?

```go
var s discord.Snowflake
s = 123

d := api.SomeStructWithASnowflakePointer{
    Snowflake: &s
}
```

Assumingly following the same idea, some slices also got pointerized, which makes also no sense, as slices can be nil by default, and creating pointers to them bears many disadvantages, like `for ... range` not working.

The same goes for `json.OptionString` which in theory makes sense, but is not required at all, as all string fields where `OptionString` is used (at least now, I haven't looked through the potentially affected fields), would never be empty, if chosen to use.

On a side note, I discovered that the `ModifyGuildData.Name` shouldn't have the `omitempty` tag. While it won't make any difference as the discord API will return an error anyways, it still help with clarity.

**Comment by diamondburned** [comment]
Go's json actually treats both a nil slice and a zero-length slice as empty, so omitempty would omit that.

Sometimes, a nullable and optional snowflake is also needed. Having it as a pointer solves this.

**Comment by diamondburned** [comment]
Here's an example. Take [UpdateStatusData](https://godoc.org/github.com/diamondburned/arikawa/gateway#UpdateStatusData)'s Activities field.

This field is required to either not be present, meaning it wouldn't be updated, or it has to be an empty slice, clearing out the user status, or a slice with Activity in it, setting a new status.

This playground link should demonstrate that a `[]T` wouldn't work in this case: https://play.golang.org/p/lljPmhfgvL6.

```go
type T struct {
	Slice1 []string  `json:"slice1,omitempty"` // non-nil slice
	Slice3 *[]string `json:"slice3,omitempty"` // non-nil pointer and slice
}
```

The above structure, when marshaled with a length 0 slice, would give the following JSON:

```json
{"slice3":[]}
```

As shown, the zero-length slice does not get marshalled into an empty slice and instead gets omitted, while the pointer slice gets marshalled as expected.

**Comment by mavolin** [comment]
> Go's json actually treats both a nil slice and a zero-length slice as empty, so omitempty would omit that.
But afaik there is no case in which an empty slice would cause a different behavior than an omitted slice.

> Sometimes, a nullable and optional snowflake is also needed. Having it as a pointer solves this.

Of course, but seeing as there neither are and nor will be any Snowflakes with the value `0` (the timestamp alone would prevent that), a Snowflake with its zero value would fully suffice and reduce the amount of extra work and inelegance by this solution. Or am I missing a case where this does not apply?

**Comment by diamondburned** [comment]
A zero snowflake actually marshals into null:

```go
func (s *Snowflake) MarshalJSON() ([]byte, error) {
	var id string

	switch i := int64(*s); i {
	case -1: // @me
		id = "@me"
	case 0:
		return []byte("null"), nil
	default:
		id = strconv.FormatInt(i, 10)
	}

	return []byte(`"` + id + `"`), nil
}
```

**Comment by mavolin** [comment]
Ok, I see, and I'm starting to hate go for this. Sorry for bothering with the other, I should probably check the docs before I create an issue complaining about something. ^^

But in the interest of keeping it simple, (`nil = omit` and `0 = null`), wouldn't it make more sense to make use 0 for omit and declare a `var SnowflakeNull Snowflake = 1`, seeing as `1` will also never be used. And explicitly writing &0 for null, is kinda contrary.

**Comment by diamondburned** [comment]
Changing 0 to 1/-1 for null would probably break a lot of things. I think it's a good idea too, buuuttt...

**Comment by diamondburned** [comment]
On second thought, we could probably make anything less than 1 be null. `-1` wouldn't count as empty, thus would be kept.

```go
//      v No longer a pointer
func (s Snowflake) MarshalJSON() ([]byte, error) {
	if s < 1 {
		return []byte("null"), nil
	} else {
		return []byte(`"` + strconv.FormatInt(i, 10) + `"`), nil
	}
}

**Comment by mavolin** [comment]
That sounds great and way better than Snowflake pointers. Thanks for being open to suggestions, unfortunately many maintainers tend to get pissed at stuff like this.

**Comment by diamondburned** [comment]
-1 null Snowflake added in 55323ee7534d7c1a545249532c148caf3b75a056

**Comment by diamondburned** [comment]
> On a side note, I discovered that the ModifyGuildData.Name shouldn't have the omitempty tag. While it won't make any difference as the discord API will return an error anyways, it still help with clarity.

[Discord documented Modify Guild as having all fields being optional](https://discord.com/developers/docs/resources/guild#modify-guild), so I'm not sure what's wrong here.

Maybe you were confusing it with `CreateGuildData`?

**Comment by mavolin** [comment]
Nah I'm just dumb. Discord normally uses a question mark for optional fields, but if all fields are optional they just write a comment and don't bother to add the question mark.

**Comment by mavolin** [comment]
Could the `NullT` constant syntax be extended to the types `ExplicitFilter`, `Notification`, and `Verification`, as they still require the complicated usage below?

```go
var f ExplicitFilter = 1

SomeStructUsingThis {
    ExplicitFilter = &f
}
```

If you approve, I'm happy to hand in a PR implementing the changes.

**Comment by diamondburned** [comment]
Yeah, sounds good to me. You should also extend it to all positive-only integer types such as Milliseconds, if possible.

**Comment by mavolin** [comment]
Considering there are multiple custom types, many of which share the same underlying types, I'd suggest creating a type that implements the `json.Marshaller` and `json.Unmarshaller` interfaces and provides the nullable option.
Does a `nullable` package, with types like `nullable.Int8` etc. in `utils` sound good to you?

**Comment by diamondburned** [comment]
That should be `json`, though I've been meaning to make a `json/option` package, so sure, that'll do. Call it `option` though, since current optional types are already `json.OptionT`.

**Comment by mavolin** [comment]
But wouldn't the type's namespace collide, seeing as we already have types like `json.OptionInt`? Also, as `OptionT` types work quite differently (pointers to types with functions to create them) compared to the types with a `NullT` constant, that is checked for during (un-) marshaling, shouldn't they get another name or package?

Btw I can refactor the current option types and put them into an option package, shouldn't be to time-consuming and matches the topic of the PR.

**Comment by diamondburned** [comment]
It would be moving `OptionInt` and such into `package option`, so I don't see how they would collide. Those default `OptionT` that are pointers to types can be kept, but you could also make an `OptionalPosInt` type (I'm terrible at naming) that would use a `NullT`.

Basically, keep `OptionT`'s implementations abstracted, so `NullT` shouldn't make a lot of difference (other than replacing `nil` with `NullT`, if you know what I mean). You can go ahead and do the PR.

P/S: sorry for the late response, I was doing #24 and forgot about this one :(

**Comment by mavolin** [comment]
Oh, now I see where you are going.

First of all, I apparently was to tired yesterday to realize that the pointers for those types aren't to produce `null` (idk how I got that idea) but to make them omittable.
This, however, makes the whole situation a bit more complicated, since we cannot use the option types for those purposes, as not all `discord.Verification` types are omittable and therefore, updating the type to `type Verification option.Uint8` wouldn't be much help.
I'd suggest making the default values variables instead of constants, so they can be referenced as pointers, as this seems like the most elegant way to me.

```go
api.ModifyGuildData{
    ...
    Verification: &LowVerification,
    ...
}
```

Secondly, we can then move the `OptionT` types to the option package, but those new types won't be needed.

And lastly, no worries for replying late, we are in completely different timezones (I'm from Germany, so there's a -6 h time difference), and I would have called it a day after my last reply anyways, considering it was nearly 4:00 am.

**Comment by mavolin** [comment]
Maybe misunderstood, but wouldn't types like `option.Uint` and `option.PosUint` be a bit hard to differentiate for the user, as the types with `NullT` are omittable and nullable, in comparison to the `option.T` types which are just omittable. Or did you actually mean that they should be separated in a `json/option` package and a `json/nullable` package?

Also, I forgot to mention, that this change would require that the types affected to don't store their default as constants, but as variables so that all in all this works:

```go
package utils/json/nullable

type Int8 int8

// Int8Null will be serialized to JSON null and may therefore not be used
// as a value itself.
const Int8Null = -1

func Int8ToJSON(i Int8) ([]byte, error) {
	if i == Int8Null {
		return []byte("null"), nil
	} else {
		return []byte(strconv.Itoa(int(i))), nil
	}
}

func Int8FromJSON(b []byte) (Int8, error) {
	s := string(b)

	if s == "null" {
		return Int8Null, nil
	} else {
		atoi, err := strconv.Atoi(s)
		return Int8(atoi), err
	}
}
```

```go
package discord

type Verification nullable.Int8

var (
	// NullVerification marshals to JSON null and may only be used for types
	// that are nullable.
	NullVerification Verification = Verification(nullable.Int8Null) // -1
	NoVerification Verification = 0
	// LowVerification requires a verified email
	LowVerification Verification = 1
	// MediumVerification requires the user be registered for at least 5
	// minutes.
	MediumVerification Verification = 2
	// HighVerification requires the member be in the server for more than 10
	// minutes.
	HighVerification Verification = 3
	// VeryHighVerification requires the member to have a verified phone
	// number.
	VeryHighVerification Verification = 4
)

// Go doesn't allow to inherit UnmarshalJSON and MarshalJSON from Int8, so we have to
// manually implement them.
// And since we can't convert a pointer of one type to a pointer of another type, we
// might as well just use Int8FromJSON and Int8ToJSON instead of having to do multiple
// type conversions.
func (v *Verification) UnmarshalJSON(b []byte) error {
	i, err := Int8FromJSON(b)
	*v = Verification(i)

	return err
}

func (v Verification) MarshalJSON() ([]byte, error) { return Int8ToJSON(Int8(v)) }
```
```go
api.ModifyGuildData{
    Verification: &NullVerification, // type *Verification
}
```

I think the var option is actually the one with the smallest tradeoff, seeing as otherwise syntax like this will be required: `Verification: *Verification(nullable.Int8(NullVerification))`

Btw, no worries with replying late, we are in different time zones (I'm from Germany, so -6 h), and it was nearly 4 am when I last replied, so I would have continued the conversation later anyways.

**Comment by diamondburned** [comment]
I think something like the Verification constant could be a type alias to avoid boilerplate when using `NullInt8`: https://play.golang.org/p/lvgybZ--2Se.

Also, I agree on making an `option` and `null` type, though it seems to me those two behave pretty much the same with the difference being the JSON tags, not the actual implementation of their types. Maybe they could be made the same?

**Comment by mavolin** [comment]
First of all we still need a bitsize of 8, according to the docs:
> The bitSize argument specifies the integer type that the result must fit into. Bit sizes 0, 8, 16, 32, and 64 correspond to int, int8, int16, int32, and int64. If bitSize is below 0 or above 64, an error is returned.

**Comment by diamondburned** [comment]
That's weird, because the playground runs :thinking:

**Comment by mavolin** [comment]
I have updated my comment.

**Comment by mavolin** [comment]
Regardless of the differences, should I name the int8 nullable type Uint7 or Uint8, considering that the 8th bit can't really be used.

**Comment by mavolin** [comment]
As this also fits the PR, should I pointerrize/use the respective option types for all optional fields, as some haven't been changed yet?

**Comment by diamondburned** [comment]
Yeah, I think that'll do (RE use respective option types). I think Uint7 is a weird name, I'd use `option.Enum` or something. Int8 and Uint7 are both kind of weird names, I think.

**Comment by mavolin** [comment]
So no `nullable` package after all, but all in `option`?

**Comment by diamondburned** [comment]
I think a `null` package is fine. I'm fine with either, really.
