### ISSUE TITLE
v3: unaligned 64-bit atomic operation on RPi 4

### ISSUE THREAD

**Issue by itslychee** [diamondburned/arikawa#297]
So i was running my bot on my RPi 4 model B and after 15-20 seconds of a seemingly successful execution, Go out of nowhere panicked. I doubled check to ensure that I was not the one at fault here, but judging from the stack trace, I highly doubt it.

Here's the error
```
panic: unaligned 64-bit atomic operation

goroutine 13 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x28de03c)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:286 +0x14
github.com/diamondburned/arikawa/v3/internal/heart.(*AtomicDuration).Get(...)
        /home/pi/go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.0.0-rc.3.0.20211202212147-07a2c407e0f2/internal/heart/heart.go:40
github.com/diamondburned/arikawa/v3/internal/heart.(*Pacemaker).Pace(0x28de03c)
        /home/pi/go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.0.0-rc.3.0.20211202212147-07a2c407e0f2/internal/heart/heart.go:117 +0x4c
github.com/diamondburned/arikawa/v3/utils/wsutil.(*PacemakerLoop).startLoop(0x28de03c)
        /home/pi/go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.0.0-rc.3.0.20211202212147-07a2c407e0f2/utils/wsutil/heart.go:111 +0x15c
github.com/diamondburned/arikawa/v3/utils/wsutil.(*PacemakerLoop).StartBeating.func1(0x249fca8, 0x28de03c)
        /home/pi/go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.0.0-rc.3.0.20211202212147-07a2c407e0f2/utils/wsutil/heart.go:81 +0x1c
created by github.com/diamondburned/arikawa/v3/utils/wsutil.(*PacemakerLoop).StartBeating
        /home/pi/go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.0.0-rc.3.0.20211202212147-07a2c407e0f2/utils/wsutil/heart.go:81 +0x1d8
```

* I am currently using the latest commit (@07a2c40) on the v3 branch 
* The software on my RPi is up-to-date
* Go version is `1.17.4`, but I remember that this had happen at the beginning of my bot's development with an earlier version, although I was too lazy to report it back then.
* CPU Architecture: `armv7l`

If any information/testing is needed, then feel free to ask!

**Comment by karitham** [comment]
Do you have any other OS information for your RPi? Is your OS 64 bit ?

**Comment by itslychee** [comment]
I feel stupid, according to [this](https://forums.raspberrypi.com/viewtopic.php?t=251721#p1536258) it seems if it isn't 64-bit, although I thought it was. Sorry for this basic overlook.

Thanks!
