### ISSUE TITLE
Support for Guild Scheduled Events

### ISSUE THREAD

**Issue by ClayMav** [diamondburned/arikawa#304]
With the addition of Scheduled Events, this would be useful to have in the library.
https://discord.com/developers/docs/resources/guild-scheduled-event#create-guild-scheduled-event

**Comment by itslychee** [comment]
I could implement this if it already isn't

**Comment by itslychee** [comment]
#319

**Comment by diamondburned** [comment]
Closed by https://github.com/diamondburned/arikawa/pull/319.
