### ISSUE TITLE
Unclear how to get users current voice channel

### ISSUE THREAD

**Issue by ClayMav** [diamondburned/arikawa#305]
Looking for help finding what voice channel a user is in, in other languages' libraries it is `guildmember.voice.channel`, but the discord.Member struct does not contain the field Voice. What is the best way to go about getting this information?

**Comment by sepruko** [comment]
You can use `discord.VoiceState`. Questions should be directed to [discussions](https://github.com/diamondburned/arikawa/discussions/categories/help) and not issues.
