### ISSUE TITLE
Stickers Unpopulated

### ISSUE THREAD

**Issue by Jayqe** [diamondburned/arikawa#306]
As I was told on Discord earlier, the `Stickers` array in discord's message struct has been [deprecated in favour of sticker_items](https://discord.com/developers/docs/resources/channel)

**Expected Behaviour**
Stickers in incoming messages should be accessible

**Actual Behaviour**
`Message.Stickers` for incoming messages is empty.

**Comment by diamondburned** [comment]
Fixed in 3fe7fbc.
