### ISSUE TITLE
`message.GuildID.IsNull()` returns false for direct messages, despite being an empty string when printed

### ISSUE THREAD

**Issue by 5HT2** [diamondburned/arikawa#318]
I don't know if this is a bug or just unintended behavior, but `message.GuildID.IsNull()` returns false for direct messages, despite being an empty string when printed.

I would *expect* it to return true in this context.

Is this intentional? If so, would you consider changing this behavior?

**Comment by diamondburned** [comment]
You should use `IsValid()`. `IsNull()` is rarely ever useful, especially when Discord is loose about it.

**Comment by 5HT2** [comment]
Welp, that works I guess. Thank you for explaining.
