### ISSUE TITLE
Discord: incomplete Invite type

### ISSUE THREAD

**Issue by mavolin** [diamondburned/arikawa#32]
The Invite type seems to be unfinished in 2 regards:
1. The Inviter field seems to be missing (See [here](https://discord.com/developers/docs/resources/invite#invite-object) for docs on this)
2. There is an InviteMetadata struct with the additional Metadata that would be filled when fetching channel and guild invites, but it is unused, making Invite effectively lack those fields.

Can hand in a PR for this, just need to know if I should let `Invite` inherit `InviteMeta` like below, or if I should create a dedicated `MetaInvite` that has those fields and that is returned by `ChannelInvites` and `GuildInvites`.

**Comment by diamondburned** [comment]
You should go with composition/inheritance, it's cleaner.
