### ISSUE TITLE
User object for a member is empty, meanwhile other fields are filled

### ISSUE THREAD

**Issue by 5HT2** [diamondburned/arikawa#327]
I'm not sure if this is an error on my part or the library, I checked the code for assigning a member object and it appears to directly deserialize discord's api response.

I'm receiving a `e *gateway.MessageCreateEvent`. I'm passing `e.Member` to a function to compare against the member's roles and IDs. 

For some reason, `e.Member.User` is blank. As in, the values are unset. Attempting to print it gives `{    false false 0 0 0 false false    #000000}`.

Therefor, I cannot get `e.Member.User.ID`, and as a result I also have to pass `e.Author` to use `e.Author.ID`.

I'm really confused as to why this is, my bot is only in one server (for testing), and it shouldn't be an intent thing.

**Comment by topi314** [comment]
This is totally normal and common practise from discord to omit the user field in the member object if the user is already provided on the parent object
```json
{
    "user": {...},
    "member": {
        user: null,
        ...
    }
}
```

**Comment by 5HT2** [comment]
Oh. Well it's unfortunate that it isn't immediately obvious what's going on. Thank you for explaining.

**Comment by diamondburned** [comment]
The library should still duplicate the object in the handler somewhere. I believe there's already a place to do this, but I'll get to it.

**Comment by 5HT2** [comment]
Oh, thank you!

**Comment by diamondburned** [comment]
I read more into the source code. If you added your handler using `*state.State` or anything that inherits it, then your `.Member.User` object should already be set:

https://github.com/diamondburned/arikawa/blob/15c37ad341cd17d712f803a0c90fd65e2bb88cd9/state/state_events.go#L33-L37

**Comment by 5HT2** [comment]
I did not, I'm only calling handlers as the examples do, with a slight modification for registration

Calling:
https://github.com/5HT2/taro-bot/blob/9d0899fffa640b070c72adb8dbf38b008adf674f/plugins/plugins.go#L139

Using:
https://github.com/5HT2/taro-bot/blob/9d0899fffa640b070c72adb8dbf38b008adf674f/plugins/example/main.go#L111

This issue happened before I added the type casting, too

**Comment by diamondburned** [comment]
[Your `Client` is a `session.Session`](https://github.com/5HT2/taro-bot/blob/9d0899fffa640b070c72adb8dbf38b008adf674f/bot/shared.go#L22). `Session` is usually kept free of things like patching events simply because its only job is to combine `api.Client` and `gateway.Gateway`.

When making a bot, 99.9% of the time you'd want to use `state.State`.

**Comment by 5HT2** [comment]
> [Your `Client` is a `session.Session`](https://github.com/5HT2/taro-bot/blob/9d0899fffa640b070c72adb8dbf38b008adf674f/bot/shared.go#L22). `Session` is usually kept free of things like patching events simply because its only job is to combine `api.Client` and `gateway.Gateway`.
> 
> When making a bot, 99.9% of the time you'd want to use `state.State`.

Ahhhhh, I didn't know that. Thank you for explaining :)

**Comment by 5HT2** [comment]
I suppose this should be closed if it is already filled when using a `state.State` handler? Thank you again
