### ISSUE TITLE
Improperly named JSON fields in TextInputComponent

### ISSUE THREAD

**Issue by DemmyDemon** [diamondburned/arikawa#333]
[These values](https://github.com/diamondburned/arikawa/blob/v3/discord/component.go#L501-L502) are named wrong.

According to [the Discord documentation](https://discord.com/developers/docs/interactions/message-components#text-inputs-text-input-example), they should be named `min_length` and `max_length`.

**Comment by diamondburned** [comment]
Huh. How the hell did this even happen?
