### ISSUE TITLE
`gateway.Gateway.Latency()` appears to be broken

### ISSUE THREAD

**Issue by Serpentiel** [diamondburned/arikawa#373]
I'm trying to call `gateway.Gateway`'s `Latency()` method the following way:

```go
	Handler: func(s *state.State) cmdroute.CommandHandlerFunc {
		return func(ctx context.Context, cmd cmdroute.CommandData) *api.InteractionResponseData {
			return &api.InteractionResponseData{
				Embeds: util.Embeds(
					fmt.Sprintf("🏓 Pong! Bot's latency to Discord is %dms.", s.Gateway().Latency().Milliseconds()),
				),
			}
		}
	},
```

which results in:

![image](https://user-images.githubusercontent.com/18222223/218096316-fcf6d8a0-3e6e-4711-b3ae-8dcc2b992b65.png)

might be related to #360

**Comment by diamondburned** [comment]
Closing this since I believe it's fixed on https://github.com/diamondburned/arikawa/commit/23140acf875671f6a7c479bbeb69944f212d83ec.
