### ISSUE TITLE
Unable to instrument API call

### ISSUE THREAD

**Issue by syrm** [diamondburned/arikawa#406]
Hello,

I'd like to be able to instrument (uptrace, opentelemetry) the API calls made to Discord by Arikawa, to be able to analyze which part of my code is slow, or if it's the Discord API that's at fault.
But for the moment, it seems impossible to do this, as the code is not adapted to it.

Do you have any plans to do this?

**Comment by diamondburned** [comment]
Hi, how would you want the code to be changed in order for this to be applicable?

Currently, Arikawa has a `PreRequest` and `PostRequest` API in the `httputil.Client` type that you should be able to use to inject a tracing middleware. You should also be able to access the context passed into `client.WithContext`.

**Comment by syrm** [comment]
Let me show an example of problem : 
```go
r.AddFunc("ping", func(ctx context.Context, data cmdroute.CommandData) *api.InteractionResponseData {
	ctx, span := tracer.Start(ctx, "operation-name")
	// big code that takes time
	span.End()
	return &api.InteractionResponseData{Content: option.NewNullableString("Pong!")}
})
```
To instrument API call time, properly, I need to use ctx or span to build an event for this ctx/span.
I'm not able to retrieve this ctx/span in httputil.Client

**Comment by diamondburned** [comment]
Ah, for `cmdroute` specifically. I think in this case, you should do 2 things:

1. Wrap `cmdroute.Router` behind a wrapper that also implements `webhook.InteractionHandler`, then add a trace there (perhaps name it `command-routing`), then
2. Create a top-level middleware that adds another trace (perhaps `command-route-handler`).

Subtracting `command-route-handler` from `command-routing` should give you the overhead of `cmdroute` including the API call required to do this.

The API call itself should still be made over `PreRequest`, FYI. They all should be sharing the same client.

**Comment by syrm** [comment]
Seems lots of work to do to instrument.
Is it possible to envisage a more cleaner/simpler way to do this ?

**Comment by diamondburned** [comment]
I don't think the router is getting first-class support for tracing anytime soon, but I also don't think it's necessarily a lot of code.

**Comment by diamondburned** [comment]
This should work:

```go
// TraceCommandRouter injects tracing into a cmdroute.Router.
// The name is used as the span name.
// A new handler is returned that should be used instead of the original.
func TraceCommandRouter(name string, r *cmdroute.Router) webhook.InteractionHandler {
	r.Use(func(next cmdroute.InteractionHandler) cmdroute.InteractionHandler {
		return cmdroute.InteractionHandlerFunc(func(ev *discord.InteractionEvent) *api.InteractionResponse {
			span := tracer.StartSpan(name + "-handler")
			defer span.Finish()
			return next.HandleInteraction(ev)
		})
	})

	return cmdroute.InteractionHandlerFunc(func(ev *discord.InteractionEvent) *api.InteractionResponse {
		span := tracer.StartSpan(name + "-router")
		defer span.Finish()
		return r.HandleInteraction(ev)
	})
}
```

Usage:

```go
r := cmdroute.NewRouter()
h.AddInteractionHandler(tracer.TraceCommandRouter("discord-interactions", r))

// use r as usual
r.Add(...)
r.Add(...)
r.Add(...)

**Comment by syrm** [comment]
Thank you for taking the time to help me.
I'm sorry for the delay but it took me a long time to get your proposal to work (I'm not very good at it).

With your solution I can't retrieve the command name to make a clean trace.
And I want to instrument the time of my code and the time of the API call separately (but in the same trace), not a sum of the two. I don't think your solution can do that.

**Comment by diamondburned** [comment]
You should definitely be able to get the command name from `ev`, but the router doesn't expose that anywhere. Beyond routing, it doesn't really care what the command name is.

A non-intrusive API could be to expose the internal `(*cmdroute.Router, string)` pair that is used for routing and tuck it in a context, but I'm not too sure about that myself. Also, middlewares don't have access to that context anyway.

Another way to do this would be to add `r.Group` and `r.With` so that we're able to do

```go
r.Group(func(r *cmdroute.Router) {
    r.Use(trace("group1"))
    r.Add(...)
})
r.With(trace("group2")).Add(...)
```

But this API isn't a thing yet.

**Comment by syrm** [comment]
Ok, thank you for your help anyway :-)

**Comment by syrm** [comment]
Thanks for all your help
