### ISSUE TITLE
API: Deprecate FormatEmojiAPI in favor of a simpler function

### ISSUE THREAD

**Issue by mavolin** [diamondburned/arikawa#42]
`FormatEmojiAPI` takes two parameters, the first one being optional, which is not very idiomatic.
Also `FormatEmojiAPI` doesn't even return a `EmojiAPI` type, but a `string`.
Also, if we're doing this `APIEmoji` might be a better name, since this is an emoji used by the API and not an API for emojis.
Therefore, I propose to either deprecate or delete `FormatEmojiAPI` in favor of two new functions:

```go
func NewAPIEmojiFromGuildEmoji(id discord.Snowflake, name string) APIEmoji {
    return name+":"+id.String()
}

func NewAPIEmojiFromUnicode(emoji string) APIEmoji {
    return name
}
```

Additionally, `APIEmoji` should get a `URLEncode() string` method, that URL encodes the emoji for safe API usage.

Can hand in a PR for this

**Comment by diamondburned** [comment]
You're only supposed to use `NewAPIEmoji` for custom emojis anyway, there's no point in using it for normal emojis. This could be documented instead of having a dummy function return the same string.

**Comment by mavolin** [comment]
But it's used by `React` which allows reactions with custom and with built in/unicode emojis.

**Comment by diamondburned** [comment]
Well, yes, but APIEmoji is just a type alias to string; it's only meant to add extra connotation on the differences of syntax for custom emojis between contexts (messages, in code, in API).

**Comment by mavolin** [comment]
K, I'll replace it with a comment
