### ISSUE TITLE
Responding interaction with no CommandHandler return value

### ISSUE THREAD

**Issue by FlowingSPDG** [diamondburned/arikawa#436]
Hello, thank you for developing and maintaining this awesome framework!

I am developing my side-project as fun, and using Clean Architecture.
my usecase method does not return any value, instead, it relays to presenter for response.
something like this:

```go

type MyUsecase interface {
	Handle(ctx context.Context, someInputValue string, presenter MyPresenter) error
}

type MyPresenter interface {
	Handle(ctx context.Context, someOutputValue string) error
}

type myUsecase struct {}

func (uc *myUsecase) Handle(ctx context.Context, someInputValue string, presenter MyPresenter) error {
	// handle usecase...
	someOutputValue := someInputValue

	// relay to presenter
	if err := presenter.Handle(ctx, someOutputValue ); err != nil {
		return err
	}

	return nil
}

```

and I wanted to use this interface, howerver ``func (r *cmdroute.Router) AddFunc`` responds to a interaction by returning ``*api.InteractionResponseData`` so I cannot use my usecase.

Is there any method that responds to interaction without returning value? (something like ``c.JSON(map[string]any)`` in gin-gonic/gin.)

This is what I tried but I am not sure this is nice way to do this:

```go

type myPresenter struct{
	ch chan<- *api.InteractionResponseData}
}

func (p *myPresenter) Handle(ctx context.Context, someOutputValue string) error {
	data := &api.InteractionResponseData{
		Content:         option.NewNullableString("USING CHANNEL!?"),
	}
	p.ch <- data
	return nil
}

func NewMyPresenter() (presenter MyPresenter, chan *api.InteractionResponseData) {
	ch := make(chan *api.InteractionResponseData, 1)
	return &myPresenter {
		ch: ch,
	}, ch
}
```

```go
func (h *CommandHandler) cmdCreate(ctx context.Context, data cmdroute.CommandData) *api.InteractionResponseData {
	presenter, ch := NewMyPresenter()
	log.Println("start Handle", data)
	if err := h.MyUsecase.Handle(ctx, "some input", presenter); err != nil {
		ch <- errorResponse(err)
	}
	ret := <-ch
	log.Println("Got channel", data)
	return ret
}
```

I'm sorry if I missed something on document.

Thanks!

**Comment by FlowingSPDG** [comment]
Sorry, I think I missed good example for this case
https://github.com/diamondburned/arikawa/blob/v3/0-examples/buttons/main.go

**Comment by diamondburned** [comment]
> Sorry, I think I missed good example for this case https://github.com/diamondburned/arikawa/blob/v3/0-examples/buttons/main.go

This example doesn't use the cmdroute, but I don't particularly recommend it if you already are using cmdroute. You can still use both at the same time, but there's probably a better way.

> ```go
> func (h *CommandHandler) cmdCreate(ctx context.Context, data cmdroute.CommandData) *api.InteractionResponseData {
> 	presenter, ch := NewMyPresenter()
> 	log.Println("start Handle", data)
> 	if err := h.MyUsecase.Handle(ctx, "some input", presenter); err != nil {
> 		ch <- errorResponse(err)
> 	}
> 	ret := <-ch
> 	log.Println("Got channel", data)
> 	return ret
> }
> ```

I don't particularly recommend doing this, as `presenter` may never be called, or it may be stored past the lifetime of the bot. 

The implementation for `AddInteractionHandler` gives you a bit of an idea for how to replicate this:

https://github.com/diamondburned/arikawa/blob/5aaffc368786d34001ec93bd7bd348fd4441b48f/session/session.go#L379-L389

With that, you're better off doing something like:

```go
type interactionResponsePresenter struct {
  state *state.State
  data  cmdroute.CommandData
}

func (p *interactionResponsePresenter) Present(ctx context.Context, data string) error {
  return s.RespondInteraction(p.data.Event.ID, p.data.Event.Token, newInteractionResponseFromData(data))
}
```

then

```go
func (h *CommandHandler) cmdCreate(ctx context.Context, data cmdroute.CommandData) *api.InteractionResponseData {
  presenter := &interactionResponsePresenter{h.state, data}
  if err := h.MyUsecase.Handle(ctx, "some input", presenter); err != nil {
    return newErrorInteractionResponse(err)
  }
  return nil // presenter will respond for us.
}
```

**Comment by diamondburned** [comment]
As a side note: consider why you're passing in a `presenter` instance instead of returning a value. With how Discord models your bots, an interaction is only ever expected to yield one response. Is there a use for why `presenter` is an argument passed in rather than a returned value?

**Comment by FlowingSPDG** [comment]
Thank you for example! Yes, that was theres no deadlock and complex channel management in a single goroutine too, awesome!

> consider why you're passing in a presenter instance instead of returning a value

Actually I could use returned value from usecase too. but I thought putting presenter into usecase could be bit easier to handle what usecase relays (and I am not sure if I was right).
what I'm working on is a game(CS2) automated tournament system, and my usecase has a bit of complicated so I thought it'd be easier to handle error, response and inputs by using presenter interface than handling errors:

```go
type StartTournamentUsecase interface{
  // this usecase can be invoked by multiple controllers such as Discord(command and button), HTTP API etc
  Invoke(ctx context.Context, ..., presenter StartTournamentPresenter) error
}

type StartTournamentPresenter interface{
  // tournament started successfully.
  Success(ctx context.Context, tournament *entity.Tournament, teams []*entity.Team, matches []*entity.Match, server []*entity.Server ) error
  // more responses since there are so many steps inside of usecase
  FailedPermissionResponse(...) error
  FailedServerResponse(...) error
}


```

Also controller/handler can focus on converting inputs only since presenter converts output.
