### ISSUE TITLE
API: add SendMessage for a simple message

### ISSUE THREAD

**Issue by mavolin** [diamondburned/arikawa#49]
Instead of sending message and embed, just send a message and add an additional `SendEmbed` method.

Can hand in a PR.

**Comment by diamondburned** [comment]
I don't really want to break the `SendMessage` API. In fact, I think the current API is perfectly reasonable.

Sorry, I don't really want to change this one.

**Comment by mavolin** [comment]
Np, how about a `SendSimpleMessage` or a `SendTextMessage` method for just content though? Seems kind of ugly to have a nil parameter for every message.

**Comment by diamondburned** [comment]
I'm fine with a `SendText` and a `SendEmbed`.
