### ISSUE TITLE
State: add FetchSync option

### ISSUE THREAD

**Issue by mavolin** [diamondburned/arikawa#76]
When requesting a resource from the state, it attempts to fetch it from the store, and if not found there starts a request against Discord's API. This quickly becomes a problem of efficiency for methods such as `Permissions`, which, in theory, could trigger up to 3 API requests consecutively, which costs a lot of time.
To improve speed I propose to add a `FetchSync` field to the `State` struct (this could also be named `FetchAsync`, but I think speed is the preferred behavior in most cases, hence default to async behavior). This means a default state will fetch all field asynchronously, starting a goroutine for each individual request, if there are more than one resources requested within a state method. Only if explicitly set to `true` the old, slower behavior will be applied.

Alternatively, this could be made default, without a way to change it.

If approved, I can hand in a PR for this.

**Comment by diamondburned** [comment]
Oh boy, this smells like Promises.

You should manually synchronize Permissions instead; there's always the option of manually checking if something is in the state.

**Comment by mavolin** [comment]
> Oh boy, this smells like Promises.

What do you think will hinder this from working correctly?

**Comment by diamondburned** [comment]
> What do you think will hinder this from working correctly?

Go's design is very anti-Promises, its entire point is to be explicit in asynchronicity. This means in a good API, the caller must have full control over that.

Not to mention, I personally hate to use Promises. It will really clutter up the API if we decide to do that.

**Comment by mavolin** [comment]
I think you misunderstood me. I didn't propose a system that returns a `Promise` but, just one that internally will parallelize the execution of two possible API requests, reducing the wait time practically in half.

Example:

```go
func (s *State) Permissions(channelID, userID discord.Snowflake) (discord.Permissions, error) {
	if s.FetchSync {
		return s.permissionsSync(channelID, userID)
	}

	return s.permissionsAsync(channelID, userID)
}

func (s *State) permissionsSync(channelID, userID discord.Snowflake) (discord.Permissions, error) {
	ch, err := s.Channel(channelID)
	if err != nil {
		return 0, errors.Wrap(err, "Failed to get channel")
	}

	g, err := s.Guild(ch.GuildID)
	if err != nil {
		return 0, errors.Wrap(err, "failed to get guild")
	}

	m, err := s.Member(ch.GuildID, userID)
	if err != nil {
		return 0, errors.Wrap(err, "failed to get member")
	}

	return discord.CalcOverwrites(*g, *ch, *m), nil
}

func (s *State) permissionsAsync(
	channelID, userID discord.Snowflake) (discord.Permissions, error) {

	ch, err := s.Channel(channelID)
	if err != nil {
		return 0, errors.Wrap(err, "Failed to get channel")
	}

	guild, guildErr := make(chan *discord.Guild), make(chan error)
	member, memberErr := make(chan *discord.Member), make(chan error)

	go func() {
		g, err := s.Guild(ch.GuildID)
		if err != nil {
			err = errors.Wrap(err, "failed to get guild")
		}

		guild <- g
		guildErr <- err
	}()

	go func() {
		m, err := s.Member(ch.GuildID, userID)
		if err != nil {
			err = errors.Wrap(err, "failed to get member")
		}

		member <- m
		memberErr <- err
	}()

	g, err := <-guild, <-guildErr
	if err != nil {
		return 0, err
	}

	m, err := <-member, <-memberErr
	if err != nil {
		return 0, err
	}

	return discord.CalcOverwrites(*g, *ch, *m), nil
}
```

**Comment by diamondburned** [comment]
This works, but 2 changes need to be done:
1. This should check for a state first before asynchronously requesting. Goroutines are cheap, but not free.
2. Given the above, Permissions could always call it asynchronously.

**Comment by diamondburned** [comment]
This should do:

```go
func (s *State) Permissions(channelID, userID discord.Snowflake) (discord.Permissions, error) {
	ch, err := s.Channel(channelID)
	if err != nil {
		return 0, errors.Wrap(err, "Failed to get channel")
	}

	var wg sync.WaitGroup

	g, guilderr := s.Store.Guild(ch.GuildID)
	if guilderr != nil {
		wg.Add(1)
		go func() {
			g, guilderr = s.Session.Guild(ch.GuildID)
			wg.Done()
		}()
	}

	m, membererr := s.Store.Member(ch.GuildID, userID)
	if membererr != nil {
		wg.Add(1)
		go func() {
			m, membererr = s.Store.Member(ch.GuildID, userID)
			wg.Done()
		}()
	}

	wg.Wait()

	if guilderr != nil {
		return 0, errors.Wrap(guilderr, "failed to get guild")
	}
	if membererr != nil {
		return 0, errors.Wrap(membererr, "failed to get member")
	}

	return discord.CalcOverwrites(*g, *ch, *m), nil
}
```
